apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-flux
  namespace: flux-system
spec:
  suspend: true
  path: ./network/traefik
  prune: true
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: cilium-flux
  decryption:
    provider: sops
    secretRef:
      name: sops-key